---
- hosts: all

- hosts: all
  gather_facts: yes
  tasks:
    - name: Change the hostname to our standard
      hostname: name="{{ inventory_hostname }}"
      when: ansible_fqdn != inventory_hostname
      become: true

    - name: restart machine
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: True
      when: reboot is defined
      become: true

    - name: Waiting for server to come back up
      local_action: wait_for host="{{ ansible_host }}" port=22 state=started

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile: state=present
        dest=/etc/hosts
        line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when: ansible_fqdn != inventory_hostname
      become: true

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: ".*{{ item }}$"
        line: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"
      become: true

    - name: Pause for 15 seconds to allow the nodes to fully come up before we validate the hostnames
      pause:
        seconds: 10

    - name: Validate ansible_hostname == inventory_hostname
      tags:
        - validate
      assert:
        that: ansible_hostname == inventory_hostname
