---
- hosts: all
  gather_facts: false
  tasks:
    - name: Create CONFIG folder
      become: true
      file:
        path: "{{ config_dir }}"
        state: directory
        owner: "{{ pg_os_user }}"
        group: "{{ pg_os_user }}"
        mode: 0770
        recurse: yes
    
    - name: Create Certificates folder
      become: true
      file:
        path: "{{ cert_dir }}"
        state: directory
        owner: "{{ pg_os_user }}"
        group: "{{ pg_os_user }}"
        mode: 0640
        recurse: yes
