---
- hosts: all

- hosts: db_server
  gather_facts: false
  tasks:
    - name: Create PostgreSQL data folder
      become: true
      file:
        path: "{{ pg_data_dir }}"
        state: directory
        owner: "{{ pg_os_user }}"
        group: "{{ pg_os_group }}"
        mode: 0770
        recurse: yes
