---
- hosts: all

- hosts: etcd_server
  gather_facts: false
  tasks:
    - name: Create ETCD data folder
      become: true
      file:
        path: "{{ etcd_data_dir }}"
        state: directory
        owner: "{{ pg_os_user }}"
        group: "{{ pg_os_user }}"
        mode: 0770
        recurse: yes