---
- hosts: all

- hosts: all
  gather_facts: false
  tasks:
    - name: Manage Repos and install auxiliary packages
      block:
      - name: Install Percona REPO DEB package
        apt:
          deb: https://repo.percona.com/apt/percona-release_latest.{{ansible_distribution_release}}_all.deb
        when: ansible_os_family == "Debian"

      - name: Select the PG Version we'll use to Install
        ansible.builtin.shell: percona-release setup ppg-{{pg_version}}

      - name: Update apt-get repo and cache
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        when: ansible_os_family == "Debian"

      - name: Upgrade all apt packages. It can take a LONG TIME
        apt: upgrade=dist force_apt_get=yes
        when: ansible_os_family == "Debian"

      - name: Install Auxiliary apps
        ansible.builtin.package:
          name:
            - vim
            - wget
            - screen
            - python3-pip
            - python3-dev
            - binutils
          state: latest

      - name: Copy the screenrc config file to host {{ inventory_hostname }}
        become: true
        ansible.builtin.template:
          src: ../templates/screenrc.t2
          dest: /root/.screenrc
          owner: root
          group: root
          mode: "0640"
      become: true
      when: hostvars[groups['ca_server'][0]]['inventory_hostname'] != inventory_hostname
