---
- hosts: all

- hosts: all
  gather_facts: no
  tasks:
    - name: Install Percona REPO DEB package
      become: true
      apt:
        deb: https://repo.percona.com/apt/percona-release_latest.{{ansible_distribution_release}}_all.deb
      when: ansible_os_family == "Debian"

    - name: Select the PG Version we'll use to Install
      become: true
      ansible.builtin.shell: percona-release setup ppg-{{pg_version}}

    - name: Update apt-get repo and cache
      become: true
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"

    - name: Upgrade all apt packages. It can take a LONG TIME
      become: true
      apt: upgrade=dist force_apt_get=yes
      when: ansible_os_family == "Debian"
